# Generated by Django 5.1.6 on 2025-02-15 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("exam", models.CharField(max_length=200)),
                ("examDate", models.DateField()),
                ("status", models.CharField(default="Active", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Programs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programs", models.CharField(max_length=300)),
                ("status", models.CharField(default="Active", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=300)),
                ("unit", models.CharField(max_length=300)),
                ("question", models.CharField(max_length=300)),
                ("difficulty", models.CharField(max_length=300)),
                ("importance", models.CharField(max_length=300)),
                ("mark", models.CharField(max_length=300)),
                ("status", models.CharField(default="Active", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=30)),
                ("semesters", models.IntegerField()),
                ("status", models.CharField(default="Active", max_length=30)),
                (
                    "Programs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.programs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionsPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QuestionNo", models.IntegerField()),
                (
                    "Exam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.exam",
                    ),
                ),
                (
                    "Questions",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.questions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regno", models.CharField(max_length=20, null=True)),
                ("name", models.CharField(max_length=30)),
                ("semester", models.CharField(max_length=50, null=True)),
                ("year", models.CharField(max_length=25, null=True)),
                ("email", models.EmailField(max_length=50)),
                ("contact", models.BigIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField()),
                ("status", models.CharField(default="Pending", max_length=30)),
                (
                    "QuestionsPaper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.questionspaper",
                    ),
                ),
                (
                    "Student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=30)),
                ("semesters", models.IntegerField()),
                ("status", models.CharField(default="Active", max_length=30)),
                (
                    "Course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aagsApp.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questions",
            name="Subjects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aagsApp.subjects",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="Subjects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aagsApp.subjects",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("contact", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questions",
            name="Teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aagsApp.teacher",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="Teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aagsApp.teacher",
            ),
        ),
    ]
