# Generated by Django 5.1.6 on 2025-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aagsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="answer",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
