# Generated by Django 5.1.4 on 2025-03-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aagsApp', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerSheet', models.FileField(upload_to='answerSheet/')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('mark', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('QuestionsPaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aagsApp.questionspaper')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aagsApp.student')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aagsApp.teacher')),
            ],
        ),
    ]
