# Generated by Django 5.1.4 on 2025-03-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aagsApp', '0004_uploadanswersheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadanswersheet',
            name='QuestionsPaper',
        ),
        migrations.AddField(
            model_name='uploadanswersheet',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aagsApp.exam'),
        ),
    ]
