# Generated by Django 5.1.6 on 2025-03-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aagsApp', '0005_remove_uploadanswersheet_questionspaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='marks',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
