# Generated by Django 5.1.6 on 2025-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aagsApp', '0006_alter_studentmark_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadanswersheet',
            name='extractedFrom',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
